version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOT_USER
      MINIO_ROOT_PASSWORD: ROOT_PASSWORD
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
